### ISSUE TITLE
Flickering when using arrows to navigate between screens

### ISSUE THREAD

**Issue by shkfnly** [goshakkk/react-native-simple-onboarding#1] opened 2016-11-28 19:27 UTC
Hey there is a flicker happening when using the arrows provided. Any thoughts on why?

**Comment by goshacmd** [comment] 2016-12-20 14:48
Hey, I don't have time to debug this for now. If you feel like it, go ahead and get to the root of it 😉

**Comment by dondragon2** [comment] 2017-06-14 02:55
was this ever resolved?

**Comment by jjingrong** [comment] 2017-12-05 06:11
Hey guys (and @shkfnly),

Just did up a bug fix for this on #9. It's caused by calling `this.setState` before `onScroll` has finished running

**Closed as completed** 2018-01-22 10:29 UTC
